ISSUIUC/MIDAS-Software

MIDAS/platformio.ini
MIDAS/src/errors.h
MIDAS/src/hardware/BackupLowG.cpp
MIDAS/src/hardware/Gyroscope.cpp
MIDAS/src/rocket_state.h
MIDAS/src/sensor_data.h
MIDAS/src/sensors.h
MIDAS/src/systems.cpp

Gets sensor data from LSM low g IMU. Sensor is implemented in `BackupLowG.cpp`. Added a new thread in `systems.cpp` for this.

[AV-1055] MIDAS Gyro / Backup LowG

---

MIDAS/src/finite-state-machines/fsm_states.h
MIDAS/src/hardware/telemetry_backend.cpp
MIDAS/src/rocket_state.h
MIDAS/src/systems.cpp
MIDAS/src/telemetry.cpp
MIDAS/src/telemetry.h
MIDAS/src/telemetry_packet.h

Change settings on lora to improve signal integrity. Shrink packet to maintain decent throughput

New telemetry packet

---

MIDAS/src/hardware/Barometer.cpp
MIDAS/src/hardware/GPSSensor.cpp

Telem fixes

---

ground/lib/RadioHead/RH_RF95.cpp
ground/src/feather/main.cpp

RF95 ground-side fix for implicit LoRa header

---

MIDAS/src/buzzer.cpp
MIDAS/src/buzzer.h
MIDAS/src/systems.cpp

Quick and dirty commit to add the landing tone indication

Landing Buzzer Sound

---

MIDAS/src/finite-state-machines/fsm.cpp
MIDAS/src/hardware/Orientation.cpp

Merge fix for commanding flight

---

MIDAS/src/hardware/Continuity.cpp
MIDAS/src/systems.cpp

Adds Nick's continuity sensing approach to flight code, updated to use more reasonable values for what we will see on launch day + sets an average on the sensor reading.

MK2.1 Pyro Continuity Sense Fix

---

MIDAS/src/hardware/Voltage.cpp
MIDAS/src/sensor_data.h

Senses the power of the board battery voltage, which will be telemetered

Board power sensing

---

ground/gss_combiner/standalone.py

Pushing merge as this is just an added script

GSS Combiner standalone thread

---

MIDAS/src/b2b_interface.cpp
MIDAS/src/b2b_interface.h
MIDAS/src/systems.cpp
MIDAS/src/systems.h
MIDAS/src/telemetry_packet.h
ground/src/feather/main.cpp

Only includes I2C functionality at the moment, but keeps the door open for CAN fixes down the line.

Add B2B communication interface for camera board

---

ground/gss_combiner/standalone.py

add logging to feather standalone

---

MIDAS/src/hardware/GPSSensor.cpp

jdsfdsfkldsf;kdfskfsdkmsdfkldsfjk;;dkk;def;kmfenj;fe ploopyjdsfdsfkldsf;kdfskfsdkmsdfkldsfjk;;dkk;def;kmfenj;fe ploopyjdsfdsfkldsf;kdfskfsdkmsdfkldsfjk;;dkk;def;kmfenj;fe ploopyjdsfdsfkldsf;kdfskfsdkmsdfkldsfjk;;dkk;def;kmfenj;fe ploopyjdsfdsfkldsf;kdfskfsdkmsdfkldsfjk;;dkk;def;kmfenj;fe ploopy fdsj;kfjnsd;lkfjdslk;fjds;kl

GPS Dynamics Fix

---

MIDAS/src/finite-state-machines/fsm.cpp
MIDAS/src/finite-state-machines/thresholds.h

changed
sustainer_idle_to_first_boost_acceleration_threshold
sustainer_ignition_to_second_boost_acceleration_threshold
sustainer_coast_detection_acceleration_threshold
sustainer_landed_vertical_speed_threshold

changed thresholds

---

MIDAS/src/hardware/SDLog.cpp

Added errors to flash chip init function

Flash Initialization Fix

---

MIDAS/src/gnc/ekf.cpp
MIDAS/src/gnc/ekf.h
MIDAS/src/systems.cpp

Changes to fix issues with gravity force and more memory efficient

fixed gravity issues and splined aerodynamic coeff data into a function

---

MIDAS/src/hardware/telemetry_backend.cpp
ground/src/feather/main.cpp

[Tested] MIDAS frequency change to 421.15 MHz on sustainer

---

MIDAS/src/hardware/Orientation.cpp
MIDAS/src/rocket_state.h
MIDAS/src/sensor_data.h
MIDAS/src/systems.cpp
MIDAS/src/telemetry.cpp
ground/src/feather/main.cpp

Telemeters 8 bits of camera
8 bits of roll rate
12 bits of kf position x

New telemetry data

---

MIDAS/src/b2b_interface.cpp
MIDAS/src/b2b_interface.h
MIDAS/src/systems.cpp

Add communication with CAM over b2b

add cam b2b fix

---

MIDAS/src/systems.cpp

Boot MIDAS into IDLE for aether 2

---

ground/gss_combiner/gui_main.py
ground/gss_combiner/standalone.py
ground/src/feather/main.cpp

Adds a gui for interfacing with all feathers. Includes compatibility for feather duos as well.

Add feather ui

---

eMMC/.gitignore
eMMC/src/main.cpp

Merges in changes that fix the mem offload code. 
Old code works primarily with EMMC, new code works with flash chip but can't delete ( :( )

Merge feb25 EMMC fix for aether 2 launch
